"""migrations

Revision ID: 93122f276d87
Revises: 71ff789667f2
Create Date: 2024-11-30 17:35:03.688099

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "93122f276d87"
down_revision: Union[str, None] = "71ff789667f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
